environment:
  name: staging
  service:
    name: sk-storefront
    cluster: core
    certificate_arn: arn:aws:acm:us-west-2:773713188930:certificate/c2979a7a-7b84-43ed-b3a7-24b0256a1b9f
    root_domain: staging.reactioncommerce.com
    dns_name: storefront
    desired_task_count: 2
    min_task_count: 0
    max_task_count: 8
    min_healthy_percent: 100
    max_percent: 200
    alb_listener_port: 80
    alb_listener_path: /
    alb_listener_rule_priority: 1
    alb_health_check_path: /
    task-definition:
      name: storefront
      cpu: 500
      memory: 1800
      container:
        name: storefront
        port: 4000
        image: reactioncommerce/reaction-next-starterkit
        image_tag: latest
        env_params:
        - name: INTERNAL_GRAPHQL_URL
        - name: EXTERNAL_GRAPHQL_URL
        - name: FAVICON_URL
        - name: PLACEHOLDER_IMAGE_URL_GALLERY
        - name: PLACEHOLDER_IMAGE_URL_GRID
        - name: SEGMENT_ANALYTICS_SKIP_MINIMIZE
        - name: SEGMENT_ANALYTICS_WRITE_KEY
        - name: KEYCLOAK_REALM
        - name: KEYCLOAK_CLIENT_ID
        - name: KEYCLOAK_URL
        - name: KEYCLOAK_REDIRECT_URI
        - name: STRIPE_PUBLIC_API_KEY
        - name: OAUTH2_AUTH_URL
        - name: OAUTH2_TOKEN_URL
        - name: OAUTH2_CLIENT_ID
        - name: OAUTH2_CLIENT_SECRET
        - name: OAUTH2_REDIRECT_URL
        - name: PASSPORT_SESSION_SECRET
        - name: CANONICAL_URL

